# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: j0ni.ca
email: j@lollyshouse.ca
description: > # this means to ignore newlines until "baseurl:"
  Shit, this text shows up when you drop links
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://j0ni.ca" # the base hostname & protocol for your site
twitter_username: j0ni
github_username:  j0ni

# Build settings
markdown: kramdown

collections:
  death:
    output: true
